# Generated by Django 4.0.3 on 2022-03-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='only_for_testing',
            field=models.TextField(blank=True),
        ),
    ]
